build:
  version: "2.0"

accounts:
  message: "Welcome to Capgemini accounts related QA APIs"
  contactDetails:
    name: "Solomon Thomas"
    email: "solomon.thomas@capgemini.com"
  onCallSupport:
    - "+91 9012378998"
    - "+91 9835679834"
