spring:
  config:
    activate:
      on-profile: prod

build:
  version: "1.0"

accounts:
  message: "Welcome to Capgemini accounts related PROD APIs"
  contactDetails:
    name: "Dinesh Kumar SA"
    email: "dinesh.kumar.sa@sc.com"
  onCallSupport:
    - "+91 7042569459"
    - "+91 8956783809"
