build:
  version: "3.0"

cards:
  message: "Welcome to Capgemini accounts related local APIs"
  contactDetails:
    name: "Akash Kumar Sinha"
    email: "akash.sinha@gmail.com"
  onCallSupport:
    - "+91 9036395199"
    - "+91 9934443576"
