build:
  version: "1.0"

loans:
  message: "Welcome to Capgemini loans related PROD APIs"
  contactDetails:
    name: "Dinesh Kumar SA"
    email: "dinesh.kumar.sa@sc.com"
  onCallSupport:
    - "+91 7042569459"
    - "+91 8956783809"
